name: Mirroring to Account B

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to B Repository
        uses: wearerequired/git-mirror-action@v1
        with:
          # 소스(A계정)와 목적지(B계정)를 명확하게 규격에 맞춰 분리합니다.
          source-repo: "https://github.com/${{ github.repository }}.git"
          destination-repo: "https://x-access-token:${{ secrets.TARGET_TOKEN }}@github.com/kimnioyh/hancom.git"